version: "3"
services:

# Webserver
  www1:
    # image: nginx
    build:
      context: .
      dockerfile: Dockerfile
    container_name: www1
    volumes:
     - "./web/www1:/usr/share/nginx/html"
     - "./web/nginx.conf:/etc/nginx/nginx.conf"
     - "./web/www1/logs:/var/log/nginx"
    ports:
     - "8081:80"

  www2:
    # image: nginx
    build:
      context: .
      dockerfile: Dockerfile
    container_name: www2
    volumes:
     - "./web/www2:/usr/share/nginx/html"
     - "./web/nginx.conf:/etc/nginx/nginx.conf"
     - "./web/www2/logs:/var/log/nginx"
    ports:
     - "8082:80"

  www3:
    # image: nginx
    build:
      context: .
      dockerfile: Dockerfile
    container_name: www3
    volumes:
     - "./web/www3:/usr/share/nginx/html"
     - "./web/nginx.conf:/etc/nginx/nginx.conf"
     - "./web/www3/logs:/var/log/nginx"
    ports:
     - "8083:80"

  www4:
    # image: nginx
    build:
      context: .
      dockerfile: Dockerfile
    container_name: www4
    volumes:
     - "./web/www4:/usr/share/nginx/html"
     - "./web/nginx.conf:/etc/nginx/nginx.conf"
     - "./web/www4/logs:/var/log/nginx"
    ports:
     - "8084:80"

  www5:
    # image: nginx
    build:
      context: .
      dockerfile: Dockerfile
    container_name: www5
    volumes:
     - "./web/www5:/usr/share/nginx/html"
     - "./web/nginx.conf:/etc/nginx/nginx.conf"
     - "./web/www5/logs:/var/log/nginx"
    ports:
     - "8085:80"

  www6:
    # image: nginx
    build:
      context: .
      dockerfile: Dockerfile
    container_name: www6
    volumes:
     - "./web/www6:/usr/share/nginx/html"
     - "./web/nginx.conf:/etc/nginx/nginx.conf"
     - "./web/www6/logs:/var/log/nginx"
    ports:
     - "8086:80"

# Reverse proxy
  rp:
    # image: nginx
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rp
    volumes:
     - "./rp/nginx.conf:/etc/nginx/nginx.conf"
     - "./rp/logs:/var/log/nginx"
    ports:
     - "80:80"
    depends_on:
      - "www1"
      - "www2"
      - "www3"
      - "www4"
      - "www5"
      - "www6"